### ISSUE TITLE
Interested in contributing GitHub wiki-related actions

### ISSUE THREAD

**Issue by jcbhmr** [github-actions-workflows/.github#2]
Hello! 👋

I'm "shopping" around for cool GitHub Actions organizations so that my actions aren't stuck if I loose interest in it or am not active or whatever. IDK if this organization _wants_ new projects? Sorry if I'm in the wrong spot here.

I am interested in adding GitHub Actions that would make it easy to sync a GitHub in-source folder like `/wiki/*.md` to the actual "wiki" tab on GitHub. This is useful for users who want to possibly:
- Autogenerate documentation but don't want to put it on GitHub Pages, so they put it on a wiki instead
- Allowing the normal GitHub flow of PRs + merges for wiki changes
- Letting users auto-generate other things like build data and post it to the wiki
- etc.

Particularily, there are 4 "things" that I see being useful to have actions for so that you can do something like this:

```yml
on:
  push:
    branches: "main"
    paths: wiki/**
jobs:
  source-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-cool/source-to-wiki-links@v1
      - uses: actions-cool/upload-wiki@v1
```
```yml
on:
  gollum: null
  schedule:
    - cron: "0 0 * * *"
jobs:
  wiki-to-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-cool/download-wiki@v1
      - uses: actions-cool/wiki-to-source-links@v1
      - uses: EndBug/add-and-commit@v9
```

Here's my ideas for the 4 composable actions:

- action-source-to-wiki-links: Rewrites links like `./Hello.md` to be `./Hello` since GitHub wikis don't do file extensions; also renames README.md to Home.md
- action-(publish|push|upload)-wiki: Pushes current folder or subfolder to the GitHub wiki
- action-(download|clone|pull)-wiki: Pulls the GitHub wiki to the current folder or sub folder
- action-wiki-to-source-links: Rewrites links like `./Hello` to `./Hello.(md|markdown|mdown,etc)` to work in source control; also renames Home.md to README.md
